// src/routes/create/+page.svelte
<div class="flex h-screen flex-col items-center justify-center">
	<div class="card bg-base-100 card-md w-96 shadow-sm">
		<div class="card-body">
			<h2 class="card-title">Create</h2>
			<form>
				<fieldset class="fieldset">
					<legend class="fieldset-legend">Image</legend>
					<input type="file" class="file-input" required />
					<!-- svelte-ignore a11y_label_has_associated_control -->
					<label class="fieldset-label">Max size 5MB</label>
				</fieldset>
				<input type="text" class="input mt-2 w-full" placeholder="Title (optional)" />
			</form>
			<div class="card-actions mt-5">
				<button class="btn btn-primary w-full">Create</button>
			</div>
		</div>
	</div>
</div>

// client/src/pages/Create.jsx
import React from "react";
import Navbar from "../components/Navbar";

export default function Create() {
  function handleSubmit(e) {
    e.preventDefault();
  }

  return (
    <div className="flex flex-col justify-center items-center h-full">
      <Navbar />
      <h1 className="text-5xl font-black">Create</h1>
      <form
        className="mt-10 flex flex-col gap-2 bg-base-200 p-10 rounded-2xl"
        onSubmit={handleSubmit}
      >
        <input
          type="text"
          placeholder="Title"
          className="input input-bordered w-full max-w-xs"
          required="true"
        />
        <input
          type="file"
          className="file-input file-input-bordered w-full max-w-xs"
          accept="image/*, .gif"
        />
        <button className="btn btn-primary">Create</button>
      </form>
    </div>
  );
}
