// src/routes/profile/+page.svelte
<script lang="ts">
	import { authClient } from '$lib/auth-client';

	const { data } = $props();
	const session = authClient.useSession();
</script>

<div class="flex min-h-screen items-center justify-center">
	<div class="card bg-base-100 card-md w-96 shadow-sm">
		<div class="card-body">
			<div class="avatar">
				<div class="w-20 rounded-xl">
					<img src={$session.data?.user.image} alt="profile" />
				</div>
			</div>
			<h1 class="text-xl font-bold">{$session.data?.user.name}</h1>
			<p>{$session.data?.user.bio}</p>
			<h2 class="mt-3 text-xl font-bold">Posts</h2>
			<div class="posts space-y-5">
				{#each data.posts as post}
					<div class="card bg-base-200 card-sm w-full shadow-sm">
						<figure class="px-10 pt-10">
							<img src={post.imageUrl} alt={post.title} class="rounded-xl" />
						</figure>
						<div class="card-body items-center text-center">
							<h2 class="card-title">{post.title}</h2>
						</div>
					</div>
				{/each}
			</div>
		</div>
	</div>
</div>

// client/src/pages/Profile.jsx
import React, { useEffect, useState } from "react";
import Navbar from "../components/Navbar";
import axios from "axios";
import DeleteBtn from "../components/DeleteBtn";

export default function Profile() {
  const endpoint = `${import.meta.env.VITE_BACKEND_URL}/users/me`;
  const token = localStorage.getItem("token");
  const [user, setUser] = useState({});
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    fetchUser();
  }, []);

  async function fetchUser() {
    try {
      const res = await axios.get(endpoint, {
        headers: {
          Authorization: `bearer ${token}`,
        },
      });

      setUser(res.data.user);
      setPosts(res.data.posts);
    } catch (err) {
      console.error(err);
    }
  }

  return (
    <div className="flex flex-col justify-center items-center min-h-screen">
      <Navbar />
      <div className="my-10 p-10 bg-base-200 rounded-3xl w-96">
        <h1 className="text-3xl font-black">{user.username}</h1>
        <div className="mt-8">
          <h2 className="font-bold text-2xl">Posts</h2>
          <div className="mt-2 space-y-8">
            {posts.map((post) => (
              <div className="relative" key={post._id}>
                <DeleteBtn id={post._id} fetchUser={fetchUser} />
                <img
                  src={post.imageUrl}
                  alt={post.title}
                  className="rounded-2xl w-full"
                />
                <h2 className="font-semibold text-lg">{post.title}</h2>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
